spring.application.name=trader
server.port=
spring.datasource.url=jdbc:mysql://localhost:3306/cavia_trader_db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.mapper-locations=classpath*:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

#spring mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cavia.io.team@gmail.com
spring.mail.password=diypvwsexrkuqrtv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#custom email properties
email.from.address=no-reply@trader.io
email.from.personal=Trader team
#custom member properties
member.cash.default=10000000
member.cash.reset=5000000

# JWT properties, DO NOT ADD SECRET KEY
jwt.secret.key=
jwt.token.expiration.time=